default:
  http_metas:
    content-type: text/html

  metas:
    title:        Use Scryptic - Add A Watermark to Your PDF Documents Online with Scryptic
    robots:       index, follow
    description:  Scrytic is an innovative web-based tool for adding a custom watermark to your PDF documents.  Start securing your documents and sign up with Scryptic today!
    keywords:     watermark, pdf, print pdf, add watermark pdf, add watermark to pdf, digital watermark, watermark pdf
    language:     en

  stylesheets:    [main]

  javascripts:    [jquery-1.3.min.js, app.js]

  has_layout:     on
  layout:         layout


