<?php
// auto-generated by sfPropelCrud
// date: 2009/06/11 20:31:45
?>
<?php use_helper('Object') ?>

<?php echo form_tag('account/update') ?>

<?php echo object_input_hidden_tag($account, 'getId') ?>

<?php echo submit_tag('save') ?>
<?php if ($account->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'account/delete?id='.$account->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'account/list') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'account/list') ?>
<?php endif; ?>
</form>
