<?php
// auto-generated by sfPropelCrud
// date: 2009/06/11 20:31:45
?>
<?php

/**
 * account actions.
 *
 * @package    sf_sandbox
 * @subpackage account
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class accountActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('account', 'list');
  }

  public function executeList()
  {
    $this->accounts = AccountPeer::getAll();
  }

  public function executeShow()
  {
    $this->account = AccountPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->account);
  }

  public function executeCreate()
  {
    $this->account = new Account();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->account = AccountPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->account);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $account = new Account();
    }
    else
    {
      $account = AccountPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($account);
    }

    $account->setId($this->getRequestParameter('id'));
    if ($this->getRequestParameter('deleted_at'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('deleted_at'), $this->getUser()->getCulture());
      $account->setDeletedAt("$y-$m-$d");
    }
    $account->save();

    return $this->redirect('account/list');
  }

  public function executeDelete()
  {
    $account = AccountPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($account);

    $account->setDeletedAt(time());
    $account->save();

    return $this->redirect('account/list');
  }
}
