default:
  stylesheets:    [ main, farbtastic.css ]

  javascripts:    [ jquery-1.3.min.js, rollover.js, jquery.pngfix.js, jqModal.js, jquery-ui-1.7.custom.min.js, farbtastic.js, jquery.maskedinput-1.2.2.min.js, printconfig.js, app.js ]
